// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_DROPDOWN_USERS_SUCCESS = 'GET_DROPDOWN_USERS_SUCCESS';
export const USER_PLAYLIST_SUCCESS = 'USER_PLAYLIST_SUCCESS';
export const CURRENT_USER_SUCCESS ='CURRENT_USER_SUCCESS';
export const USER_TRACK_SUCCESS='USER_TRACK_SUCCESS';



// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';
